---
- name: Cluster prep
  #hosts: k3s_cluster
  #hosts: k8s-wisma
  hosts: wisma
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Setup K3S server
  #hosts: server
  #hosts: k8s-wisma
  hosts: wisma
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  #hosts: agent
  #hosts: k8s-wisma
  hosts: wisma
  become: true
  roles:
    - role: k3s_agent
